spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/company_simulation
    username: user
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: company_simulation
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 20
      idle-timeout: 300000
      max-lifetime: 1200000